ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS purpose text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS spec text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS includes text NOT NULL DEFAULT '';